// <auto-generated />
using System;
using Gestion_Medicament.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_Medicament.Migrations
{
    [DbContext(typeof(PharmacieDbContext))]
    partial class PharmacieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_Medicament.Models.LigneLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumLiv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("RefMed")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NumLiv");

                    b.HasIndex("RefMed");

                    b.ToTable("LigneLivraisons");
                });

            modelBuilder.Entity("Gestion_Medicament.Models.Livraison", b =>
                {
                    b.Property<string>("Numero")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateLiv")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Numero");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("Gestion_Medicament.Models.Medicament", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Reference");

                    b.ToTable("Medicaments");
                });

            modelBuilder.Entity("Gestion_Medicament.Models.LigneLivraison", b =>
                {
                    b.HasOne("Gestion_Medicament.Models.Livraison", "Livraison")
                        .WithMany("Lignes")
                        .HasForeignKey("NumLiv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestion_Medicament.Models.Medicament", "Medicament")
                        .WithMany("LigneLivraisons")
                        .HasForeignKey("RefMed")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livraison");

                    b.Navigation("Medicament");
                });

            modelBuilder.Entity("Gestion_Medicament.Models.Livraison", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Gestion_Medicament.Models.Medicament", b =>
                {
                    b.Navigation("LigneLivraisons");
                });
#pragma warning restore 612, 618
        }
    }
}
